[package]
name = "jack-web-audio"
version = "0.1.0"
authors = ["Joseph Burnett <josephburnett79@gmail.com>"]

[dependencies]
jack = "0.4.0"
uuid = { version = "0.4.0", features = ["v4"] }
ws = "0.5.3"